Models/Actor.cs
using System.ComponentModel.DataAnnotations;

namespace Fall2025_Project3_jma33.Models
{
    public class Actor
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string IMDBLink { get; set; }
        public byte[]? Photo { get; set; }
    }
}

Controllers/ActorsController.cs
using Azure.AI.OpenAI;
using Fall2025_Project3_jma33.Data;
using Fall2025_Project3_jma33.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OpenAI.Chat;
using System;
using System.ClientModel;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Nodes;
using System.Threading.Tasks;
using VaderSharp2;

namespace Fall2025_Project3_jma33.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _config;

        private readonly ApiKeyCredential _apiCredential;
        private readonly Uri _apiEndpoint;
        private const string AiDeployment = "gpt-4.1-nano";

        public ActorsController(ApplicationDbContext context, IConfiguration config)
        {
            _context = context;
            _config = config;

            var apiKey = _config["ApiCredential"] ?? throw new InvalidOperationException("API credential in Azure does not exist in the current Configuration");
            var apiEndpoint = _config["ApiEndpoint"] ?? throw new InvalidOperationException("API endpoint in Azure does not exist in the current Configuration");

            _apiCredential = new ApiKeyCredential(apiKey);
            _apiEndpoint = new Uri(apiEndpoint);
        }

        private async Task<List<ActorTweetAndSentiment>> CreateActorTweetsSentiment(string actorName)
        {
            var tweets_and_sents = new List<ActorTweetAndSentiment>();
            ChatClient client = new AzureOpenAIClient(_apiEndpoint, _apiCredential).GetChatClient(AiDeployment);

            var messages = new ChatMessage[]
            {
            new SystemChatMessage($"You represent the Twitter social media platform. Generate realistic tweets about actors that could appear on social media and entertainment news. Each answer should be a valid JSON formatted array of objects containing the tweet and username. The response should start with [."),
            new UserChatMessage($"Generate 20 different tweets from a variety of users about the actor {actorName}. For the tweet content, include a mix of comments about their work, public events, social media, or general news. Keep each tweet content under 50 words.")
            };
            ClientResult<ChatCompletion> result = await client.CompleteChatAsync(messages);

            string tweetsJsonString = result.Value.Content.FirstOrDefault()?.Text ?? "[]";
            JsonArray json = JsonNode.Parse(tweetsJsonString)!.AsArray();

            var analyzer = new SentimentIntensityAnalyzer();

            var tweets = json.Select(t => new { Username = t!["username"]?.ToString() ?? "", Text = t!["tweet"]?.ToString() ?? "" }).ToArray();
            
            foreach (var tweet in tweets)
            {
                SentimentAnalysisResults sentiment = analyzer.PolarityScores(tweet.Text);
                tweets_and_sents.Add(new ActorTweetAndSentiment
                {
                    Tweet_Username = tweet.Username,
                    Tweet_Text = tweet.Text,
                    Sentiment = sentiment.Compound,
                    Sentiment_String = sentiment.Compound.ToString("F2")
                });
            }
            return tweets_and_sents;
        }

        public async Task<IActionResult> Photo(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var actor = await _context.Actor.FirstOrDefaultAsync(s => s.Id == id);

            if (actor == null || actor.Photo == null)
            {
                return NotFound();
            }

            return File(actor.Photo, "image/jpg");
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actor.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            var movies = await _context.MovieActors
                .Include(m => m.Movie)
                .Where(m => m.ActorId == actor.Id)
                .Select(m => m.Movie!)
                .ToListAsync();

            var tweetsAndSents = await CreateActorTweetsSentiment(actor.Name);
            
            var vm = new ActorDetailsViewModel(actor, movies, tweetsAndSents);

            return View(vm);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Gender,Age,IMDBLink")] Actor actor, IFormFile? Photo)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null && Photo.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Photo.CopyToAsync(stream);
                    actor.Photo = stream.ToArray();
                }
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Gender,Age,IMDBLink")] Actor actor)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.Actor.FindAsync(id);
            if (actor != null)
            {
                _context.Actor.Remove(actor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actor.Any(e => e.Id == id);
        }
    }
}

Views/Actors/Create.cshtml
@model Fall2025_Project3_jma33.Models.Actor

@{
    ViewData["Title"] = "Create";
}

<h1>Create Actor</h1>

<div class="row mt-2">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IMDBLink" class="control-label"></label>
                <input asp-for="IMDBLink" class="form-control" />
                <span asp-validation-for="IMDBLink" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Photo" class="control-label"></label>
                <input type="file" id="Photo" name="Photo" asp-for="Photo" class="form-control" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mt-2">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Actors/Delete.cshtml
@model Fall2025_Project3_jma33.Models.Actor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Actor</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Actor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IMDBLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IMDBLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Url.Action("Photo", "Actors", new { id=@Model?.Id })" width="100" height=auto />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Actors/Details.cshtml
@model Fall2025_Project3_jma33.Models.ActorDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Actor Details</h1>

<div class="mt-2">
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actor.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actor.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actor.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.IMDBLink)
        </dt>
        <dd class = "col-sm-10">
            <a href="model.Actor.IMDBLink">@Html.DisplayFor(model => model.Actor.IMDBLink)</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actor.Photo)
        </dt>
        <dd class = "col-sm-10">
            @if (@Model?.Actor.Photo != null)
            {
                <img src="@Url.Action("Photo", "Actors", new { id=@Model?.Actor.Id })" width="200" height=auto />
            }
        </dd>
    </dl>
</div>

<div>
    <h2>Movies</h2>
    <table class="table OtherInfoTables">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Movies)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary">
                            <i class="fa fa-pen" style="color: green;"></i>
                        </a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary">
                            <i class="fa-solid fa-bars" style="color: silver;"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-primary">
                            <i class="fa fa-xmark" style="color: red;"></i>
                        </a>
                        @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    </br>
    <h3 style="text-align: center;">Overall Sentiment Score: @Model.AvgSentiment</h2>
    </br>
    <h2>Recent Tweets</h2>
    <table class="table" data-table>
        <thead>
            <tr>
                <th>
                    User
                </th>
                <th>
                    Tweet
                </th>
                <th>
                    Sentiment Score
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.TweetsandSents)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tweet_Username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tweet_Text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sentiment_String)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Actor.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Actors/Edit.cshtml
@model Fall2025_Project3_jma33.Models.Actor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Actor</h1>

<div class="row mt-2">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IMDBLink" class="control-label"></label>
                <input asp-for="IMDBLink" class="form-control" />
                <span asp-validation-for="IMDBLink" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Photo" class="control-label"></label>
                <input type="file" id="Photo" name="Photo" class="form-control" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mt-2">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Actors/Index.cshtml
@model IEnumerable<Fall2025_Project3_jma33.Models.Actor>

@{
    ViewData["Title"] = "Index";
}

<h1>All Actors</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table EditTables">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IMDBLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                <a href="@item.IMDBLink">@Html.DisplayFor(modelItem => item.IMDBLink)</a>
            </td>
            <td>
                <img src="@Url.Action("Photo", "Actors", new { id=@item.Id })" width="100" height=auto />
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary">
                    <i class="fa fa-pen" style="color: green;"></i>
                </a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary">
                    <i class="fa-solid fa-bars" style="color: silver;"></i>
                </a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-primary">
                    <i class="fa fa-xmark" style="color: red;"></i>
                </a>

                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
}
    </tbody>
</table>